# Generated by Django 4.2.11 on 2024-08-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userd',
        ),
    ]
