# Generated by Django 4.2.11 on 2024-08-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_userd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userd',
            new_name='user',
        ),
    ]
