# Generated by Django 4.2.11 on 2024-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_userd_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0.001, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0.03333333333333333, max_length=128),
            preserve_default=False,
        ),
    ]
